#!/bin/bash
# setup_workspace.sh — Workspace 設定、Repo Clone、編譯
# 處理從 GitHub 取得程式碼、首次編譯、把 source 寫入 bashrc

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/utils.sh"
source "${SCRIPT_DIR}/detect.sh"

# ─── 設定 ───
export ROS_DISTRO="${ROS_DISTRO:-humble}"
export ROBOT_WS_DIR="${ROBOT_WS_DIR:-$HOME/ros2_ws}"
export REPO_URL="${REPO_URL:-https://github.com/Oren2026/special_topic.git}"
export REPO_BRANCH="${REPO_BRANCH:-ros2-crossfloor-amr}"
export ROS_WS_SRC="$ROBOT_WS_DIR/src"
export ROS_WS_INSTALL="$ROBOT_WS_DIR/install"
export ROS_WS_LOG="$ROBOT_WS_DIR/log"
export ROS_WS_BUILD="$ROBOT_WS_DIR/build"

# ─── 安裝 ───
install() {
    log_step "設定 ROS2 Workspace..."

    # 1. 確認依賴
    log_info "[1/4] 確認依賴..."
    if ! has_ros2; then
        log_error "ROS2 未安裝，請先執行 install_ros2.sh"
        return 1
    fi
    if ! has_git; then
        require_root
        apt_install git
    fi

    # 2. 建立 workspace 目錄
    log_info "[2/4] 建立 Workspace 目錄..."
    ensure_dir "$ROBOT_WS_DIR"
    ensure_dir "$ROS_WS_SRC"

    # 3. Clone 或更新 repo
    log_info "[3/4] Clone / 更新 Repo..."
    local ros2_subdir="$ROS_WS_SRC/ros2-crossfloor-amr"

    if [[ -d "$ros2_subdir/.git" ]]; then
        log_info "Repo 已存在，拉取最新..."
        cd "$ros2_subdir"
        git fetch origin
        git checkout "$REPO_BRANCH"
        git pull origin "$REPO_BRANCH"
    else
        log_info "Clone Repo 到 $ros2_subdir..."
        cd "$ROS_WS_SRC"
        # 只 clone 指定分支，節省頻寬
        git clone -b "$REPO_BRANCH" --depth 1 "$REPO_URL" "$ros2_subdir"
    fi

    # 4. 編譯
    log_info "[4/4] 首次編譯（可能需要 10-30 分鐘）..."
    # shellcheck source=/opt/ros/humble/setup.bash
    source /opt/ros/humble/setup.bash
    cd "$ROBOT_WS_DIR"
    colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release 2>&1 | tee "$ROS_WS_LOG/colcon_build.log"

    log_ok "Workspace 設定完成"
}

# ─── 更新（pull + rebuild）───
update() {
    log_step "更新 Workspace..."

    local ros2_subdir="$ROS_WS_SRC/ros2-crossfloor-amr"
    if [[ ! -d "$ros2_subdir/.git" ]]; then
        log_error "Repo 不存在，請先執行 install"
        return 1
    fi

    cd "$ros2_subdir"
    log_info "拉取最新程式碼..."
    git pull origin "$REPO_BRANCH"

    # 增量編譯
    # shellcheck source=/opt/ros/humble/setup.bash
    source /opt/ros/humble/setup.bash
    cd "$ROBOT_WS_DIR"
    colcon build --symlink-install 2>&1 | tee "$ROS_WS_LOG/colcon_update.log"

    log_ok "更新完成"
}

# ─── 寫入 bashrc ───
setup_bashrc() {
    log_step "設定 bashrc 環境變數..."

    local bashrc="$HOME/.bashrc"
    backup_file "$bashrc"

    local ros2_block='
# ============================================
# ROS2 Crossfloor AMR Workspace
# Generated by installer
# ============================================
source /opt/ros/humble/setup.bash

# Workspace
export ROBOT_WS_DIR="$HOME/ros2_ws"
if [ -f "$ROBOT_WS_DIR/install/setup.bash" ]; then
    source "$ROBOT_WS_DIR/install/setup.bash"
fi

# ROS_DOMAIN_ID（避免同網路多機器衝突）
export ROS_DOMAIN_ID=42

# Gazebo 資源路徑
export GAZEBO_RESOURCE_PATH="$ROBOT_WS_DIR/ros2-crossfloor-amr/sim/worlds:$GAZEBO_RESOURCE_PATH"

# 方便進入工作目錄
alias cdr="cd $ROBOT_WS_DIR/ros2-crossfloor-amr"
alias cdrs="cd $ROBOT_WS_DIR/ros2-crossfloor-amr/src"
alias cb="cd $ROBOT_WS_DIR && colcon build --symlink-install && source install/setup.bash"
'

    if ! grep -q "ROS2 Crossfloor AMR Workspace" "$bashrc"; then
        echo "$ros2_block" >> "$bashrc"
        log_ok "bashrc 已寫入"
    else
        log_ok "bashrc 已有設定，跳過"
    fi

    log_info "建議執行以下指令啟用環境："
    echo ""
    echo "    source ~/.bashrc"
    echo "    cdr"
    echo ""
}

# ─── 解除安裝 workspace ───
remove() {
    log_step "移除 Workspace..."
    if confirm "確定移除 $ROBOT_WS_DIR？"; then
        rm -rf "$ROBOT_WS_DIR"
        log_ok "Workspace 已移除"
    fi
}

# ─── 入口 ───
main() {
    local action="${1:-check}"

    case "$action" in
        check)   check ;;
        install) install ;;
        update)  update ;;
        bashrc)  setup_bashrc ;;
        remove)  remove ;;
        *)
            echo "用法：$0 [check|install|update|bashrc|remove]"
            exit 1
            ;;
    esac
}

main "$@"